[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "tp1viz"
version = "0.4.0"
description = "Visualización y análisis del TP1 de Sistemas de Simulación"
requires-python = ">=3.11"
dependencies = [
    "matplotlib",
    "pillow",
]

[project.scripts]
tp1viz = "tp1viz.cli:main"

[tool.setuptools.packages.find]
where = ["src"]
